name: Java CI with Maven

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package

      - name: Set Release version env variable
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: copy jar
        run: |
          mkdir lib
          mv target/*with-dependencies.jar lib/
          
          mkdir doc
          mv LICENSE doc/
          mv README.md doc/

      - name: Archive Release
        uses: montudor/action-zip@v1
        with:
          args: zip -9 -q -r kafka-connect-elasticsearch-source-${{ env.RELEASE_VERSION }}.zip lib assets etc doc manifest.json

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "kafka-connect-elasticsearch-source-${{ env.RELEASE_VERSION }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.RELEASE_VERSION }}
          makeLatest: true
          prerelease: true
          allowUpdates: true
          updateOnlyUnreleased: true
